// Generates app/icons/index.ts from the GJS app's custom symbolic icons
// (packages/app-gnome/data/icons/scalable/actions/*.svg), so the Android app can
// render the SAME Learn6502 icons via @gjsify/adwaita-nativescript's AdwIcon
// (which rasterises a symbolic SVG string with PathParser). These are the app's
// OWN icons — not generic Adwaita — so they live here, mirroring the GJS set 1:1.
//
// Run: node scripts/generate-icons.mjs   (re-run when app-gnome icons change)
import { readFileSync, writeFileSync, readdirSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const SRC = join(here, "../../app-gnome/data/icons/scalable/actions");
const OUT = join(here, "../app/icons/index.ts");

/** `open-book-symbolic.svg` → `openBookSymbolic`. */
const toCamel = (file) => file.replace(/\.svg$/, "").replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());

const files = readdirSync(SRC)
  .filter((f) => f.endsWith(".svg"))
  .sort();

const exports = files.map((file) => {
  const raw = readFileSync(join(SRC, file), "utf8");
  // Drop the XML prolog + collapse whitespace to a single line, matching the
  // @gjsify/adwaita-icons string shape (starts at `<svg`).
  const svg = raw
    .replace(/<\?xml[^>]*\?>/, "")
    .replace(/\s+/g, " ")
    .trim();
  return `export const ${toCamel(file)} = ${JSON.stringify(svg)};`;
});

const header = `// AUTO-GENERATED by scripts/generate-icons.mjs — do not edit by hand.
// Learn6502's custom symbolic icons, ported from app-gnome's icon theme so the
// Android app renders them via AdwIcon (@gjsify/adwaita-nativescript). Re-run the
// generator after changing the app-gnome icons.
`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, header + "\n" + exports.join("\n") + "\n");
console.log(`Wrote ${files.length} icons → app/icons/index.ts`);
console.log(files.map(toCamel).join(", "));
