import { AdwClamp } from "@gjsify/adwaita-web";
import type { LearnView } from "@learn6502/common-ui";
import { learnController } from "@learn6502/common-ui";
import tutorialHtml from "@learn6502/learn/dist/tutorial.html";

/**
 * AdwLearnView — the `LearnView` from `@learn6502/common-ui` implemented as a
 * class over `@gjsify/adwaita-web` custom elements, mirroring the ADR 0007
 * spike's `AdwDebuggerView` (`views/adw-debugger.ts`).
 *
 * Unlike the debugger, there is no per-widget composition here: the whole
 * tutorial is one generated HTML fragment from `@learn6502/learn`'s HTML
 * render target (`dist/tutorial.html`, built alongside the GTK `.ui` XML and
 * NativeScript XML from the SAME `tutorial.mdx` — see
 * `packages/learn/tsx/index.tsx`). This view's job is narrow: mount that
 * fragment, upgrade its `<adw-source-view>` code blocks to real CodeMirror
 * editors (the `@gjsify/adwaita-web/source-view` opt-in subpath, imported as
 * a side effect by `./index.ts`), and forward the source views' `copy`
 * events to `learnController` — exactly the seam GNOME's `TutorialView`/
 * `MdxView` and Android's `Learn` widget use
 * (`sourceView.events.on("copy", ...) -> learnController.dispatch("copy", ...)`).
 *
 * Phase 2 scope: the tutorial only, as a single scrolling document (no
 * Examples list / navigation subpages — see GNOME's `Learn`/`learn.blp` for
 * that structure, which a later phase can port). Quick-help
 * (`dist/quick-help.html`) is generated by the same learn-package target but
 * has no slot in the current shell chrome.
 */
export class AdwLearnView extends HTMLElement implements LearnView {
  private built = false;
  private lastScrollPosition = 0;

  private readonly onCopy = (event: Event): void => {
    const detail = (event as CustomEvent<{ code: string }>).detail;
    if (!detail?.code) return;
    learnController.dispatch("copy", { code: detail.code });
  };

  connectedCallback(): void {
    this.ensureBuilt();
  }

  // --- LearnView interface ---

  /** Save the current scroll position (this element is its own scroll
   * container — see `styles.ts`'s `learn-view { overflow-y: auto }`). */
  public saveScrollPosition(): void {
    this.lastScrollPosition = this.scrollTop;
  }

  /** Restore the previously saved scroll position. */
  public restoreScrollPosition(): void {
    if (this.lastScrollPosition > 0) this.scrollTop = this.lastScrollPosition;
  }

  /** Build the widget tree (once): the tutorial fragment in a clamp, matching
   * the GNOME twin's `Adw.Clamp { maximum-size: 600 }` around `TutorialView`. */
  private ensureBuilt(): void {
    if (this.built) return;
    this.built = true;

    const clamp = new AdwClamp();
    clamp.setAttribute("maximum-size", "600");
    // The fragment is trusted build output (the learn package's own MDX
    // render target), not user input.
    clamp.innerHTML = tutorialHtml;

    this.replaceChildren(clamp);
    // Fenced code blocks are `<adw-source-view>` tags in the markup above;
    // the `copy` event bubbles from any of them up through this element.
    this.addEventListener("copy", this.onCopy);
  }
}

customElements.define("learn-view", AdwLearnView);
